name: Jekyll Project
url: "/project"
destination: project
exclude: [
    "README.md",
    "*.zip",
    "*.bat",
    "sass",
    "gulpfile.js",
    "package.json",
    "node_modules",
    "TODO.*"
]
keep_files: [
    "css"
]
port: 7100